[package]
name = "pi_postprocess"
version = "0.1.0"
authors = ["bp0002 <bp950722@outlook.com>"]
edition = "2021"

[dependencies]
pollster = "0.2"
rand = "0.8"
guillotiere = {version="0.6"}
num-traits = "0.2"
lazy_static = "1.4"
derive_deref = "1.1"
env_logger = "0.9"
log="0.4"
smallvec={version = "1.8", features = ["serde"]}
wgpu = { version = "0.15", features = ["spirv", "glsl"] }
bytemuck = { version = "1.4", features = ["derive"] }
naga = { version = "0.11", features = [
    "glsl-in",
    "spv-in",
    "spv-out",
    "wgsl-in",
    "wgsl-out",
] }

pi_hash="0.1"
pi_enum_default_macro="0.1"
pi_assets = "0.11"
pi_map = "0.1"

pi_wy_rng = { git = "https://github.com/GaiaWorld/pi_wy_rng.git" }
pi_render = { git = "https://github.com/GaiaWorld/pi_render", branch = "bevy_shader"  }

pi_share = "0.4"
pi_atom = { version="0.2", features = ["serde"] }

[dev-dependencies]
winit = { git = "http://ser.yinengyun.com:10082/tech/winit.git" }
wgpu = "0.15"
image = "0.24"
env_logger = "0.9"
float-ord = "0.3"
async-trait="0.1"

# [patch."https://github.com/GaiaWorld/pi_render"]
# pi_render = { path = "../pi_render" }


# [patch."http://ser.yinengyun.com:10082/tech/winit.git"]
# winit = { path = "../winit" }

[net]
git-fetch-with-cli = true
offline = true
